const events = {
  IDEATION: [
    {
      id: "1",
      name: " Empowered Indians",
      description:" Not Available. ",
      deg: 135,
      from: "rgba(254, 253, 205, 1) 11.2%",
      to: "rgba(163, 230, 255, 1) 91%",
    },
    {
      id: "2",
      name: "[Thriving & Sustainable Economy]",
      description: " Not Available. ",
      deg: 135,
      from: "rgba(163, 230, 255, 1)",
      to: " #FFEFBA 80%",
    },
    {
      id: "3",
      name: "Innovation Science & Technology.",
      description:"Not Available. ",
      deg: 135,
      from: "#FFEFBA 40%",
      to: " #f5af19",
    },
    {
      id: "4",
      name: "Good Governance & Security.",
      description:" Not Available.",
      deg: 135,
      from: "#f5af19",
      to: "#ffffff",
    },
    {
      id: "5",
      name: "India in the World.",
      description:" Not Available.",
      deg: 135,
      from: "rgba(163, 230, 255, 1)",
      to: " #FFEFBA 80%",
    },
  ],
  "Literature Events": [
    {
      id: "1",
      name: "Glimses of India ",
      description: " India Quiz",
      deg: 135,
      from: "#ffffff",
      to: "#a8ff78",
    },
    {
      id: "2",
      name: "Thematic Collage",
      description: " Not Available. ",
      deg: 135,
      from: " #a8ff78",
      to: " #FBD786",
    },
    {
      id: "3",
      name: " Srujana",
      description: "  Creative Writing in Telugu. ",
      deg: 135,
      from: " #a8ff78",
      to: " #FBD786",
    },
    {
      id: "4",
      name: " Gab Fab",
      description: "  Extempore Floor-crossing.",
      deg: 135,
      from: " #a8ff78",
      to: " #FBD786",
    },
    {
      id: "5",
      name: "Chitra Katha",
      description: " Narration of a Picture. ",
      deg: 135,
      from: " #a8ff78",
      to: " #FBD786",
    },
    {
      id: "6",
      name: "Wrangle",
      description: " The Debate. ",
      deg: 135,
      from: " #a8ff78",
      to: " #FBD786",
    },
    {
      id: "7",
      name: "Splash of Colours",
      description: " Thematic Painting. ",
      deg: 135,
      from: " #a8ff78",
      to: " #FBD786",
    },
    {
      id: "8",
      name: "Explicit Expressions",
      description: " Standup Comedy. ",
      deg: 135,
      from: " #a8ff78",
      to: " #FBD786",
    },
  ],
  "Cultural Events": [
    {
      id: "1",
      name: " Melody Mosiac",
      description:" Singing. ",
      deg: 135,
      from: "rgba(254, 253, 205, 1) 11.2%",
      to: "rgba(163, 230, 255, 1) 91%",
    },
    {
      id: "2",
      name: "Vocal Vortex",
      description: " Not Available. ",
      deg: 135,
      from: "rgba(163, 230, 255, 1)",
      to: " #FFEFBA 80%",
    },
    {
      id: "3",
      name: "Rythmic Revelry.",
      description:"Not Available. ",
      deg: 135,
      from: "#FFEFBA 40%",
      to: " #f5af19",
    },
    {
      id: "4",
      name: "Team Tempo.",
      description:" Not Available.",
      deg: 135,
      from: "#f5af19",
      to: "#ffffff",
    },
  ],
};

export default events;
